seed: 1
batch_size: 5000
max_epochs: 100
eval_every_n: 1
lam_u: 0.1
lam_V: 0.2
data_size: 10000
val_size: 200
split_ratio: 0.5

system:
    device: -1
    dtype: 64
 
outer_optimizer:
    outer_lr: 0.001
    outer_wd: 0.1

inner_solver:
    name: 'funcBO.solvers.CompositeSolver'
    optimizer:
        name: 'torch.optim.Adam'
        lr: 0.001
        weight_decay: 0.1
    num_iter: 20

dual_solver:
    name: 'funcBO.solvers.IterativeSolver'
    optimizer:
        name: 'torch.optim.Adam'
        lr: 1.0e-05
        weight_decay: 0.1
    num_iter: 20

dual_model:
    name: 'funcBO.dual_networks.DualNetwork'
