# @package selection

name: 'ITD'
warm_start_iter : 20
unrolled_iter: 10
correction: False
compute_latest_correction: True
dual_var_warm_start: True

optimizer:
  name: 'torchopt.adam'
  lr: 0.0001 # (grid search)
  weight_decay: 0.01 # (grid search)
  betas : ${as_tuple:0.9,0.999}
  eps: 0.00000001
  eps_root: 0.0
scheduler:
  use_scheduler: False

