# @package selection

name: 'ITD'
warm_start_iter : 19
unrolled_iter: 1 # (grid search)
correction: False
compute_latest_correction: True
dual_var_warm_start: True

optimizer:
  name: 'torchopt.adam'
  #momentum: 0.0
  lr: 0.001 # (grid search)
  weight_decay: 0. # no need for this (use lam_V)
  # name: 'TorchOpt.adam'
  betas : ${as_tuple:0.9,0.999}
  eps: 0.00000001
  eps_root: 0.0
scheduler:
  #name: 'torch.optim.lr_scheduler.CosineAnnealingLR'
  #T_max: ${training.total_epoch}
  use_scheduler: False

