seed: 1
max_epochs: 100

system:
    device: -1
    dtype: 64

outer_optimizer:
    outer_lr: 0.001
    outer_wd: 0.01

inner_solver:
    name: 'funcBO.solvers.IterativeSolver'
    optimizer:
        name: 'torch.optim.Adam'
        lr: 0.001
        weight_decay: 0.01
    num_iter: 20

dual_solver:
    name: 'funcBO.solvers.IterativeSolver'
    optimizer:
        name: 'torch.optim.Adam'
        lr: 0.001
        weight_decay: 0.01
    num_iter: 20

dual_model:
    name: 'funcBO.dual_networks.LinearDualNetwork'
    input_dim: 32
    output_dim: 32
