seed: 42
max_epochs: 2
eval_every_n: 1
lam_u: 0.1
lam_V: 0.1
data_size: 5000
val_size: 0
split_ratio: 0.5

system:
    device: -1
    dtype: 64
 
treatment_optimizer:
    lr: 0.001
    wd: 0.1
    num_iter: 1

instrumental_optimizer:
    lr: 0.001
    wd: 0.1
    num_iter: 20


