seed: 42
batch_size: 2500
max_epochs: 5000
max_inner_dual_epochs: 20
max_inner_epochs: 20
eval_every_n: 1
lam_u: 0.1
lam_V: 0.2
a_star_method: "closed_form_a"
data_size: 5000
val_size: 0
split_ratio: 0.5

system:
    device: -1
    dtype: 32
 
outer_optimizer:
 outer_lr: 0.0001
 outer_wd: 0.1

inner_solver:
    name: 'funcBO.solvers.CompositeSolver'
    optimizer:
        name: 'torch.optim.Adam'
        lr: 0.0001
        weight_decay: 0.1
    num_iter: 20

dual_solver:
    name: 'funcBO.solvers.ClosedFormSolver'
dual_model:
    name: 'funcBO.dual_networks.LinearDualNetwork'



