defaults:
    - selection: BGS

seed: 1
batch_size: 2500
max_epochs: 100
eval_every_n: 1
lam_u: 0.1
lam_V: 0.2  # (grid search) ### L2 reg for all inner params (no need for weight decay in the optimizer)
data_size: 5000
val_size: 0
split_ratio: 0.5

linear: 
    in_dim: 32
    out_dim: 1

system:
    device: -1
    dtype: 64
 
outer_optimizer:
    outer_lr: 0.001
    outer_wd: 0.1